import Navbar from "./Navbar"
import Hero from "./Hero"
import CanvasLoader from "./Loader"
import About from "./About"
import Projects from "./Projects"
import Contact from "./Contact"
import Footer from "./Footer"
import ScrollUpBtn from "./ScrollUpBtn"
import ProjectCard from "./ProjectCard"
import Loading from "./Loading"
import ThemeMenu from "./ThemeMenu"
import Code from "./Code"
import Experience from "./Experience"
import ExperienceCard from "./ExperienceCard"

export { ExperienceCard, Experience, Code, Loading, Navbar, Hero, CanvasLoader, About, Projects, Contact, Footer, ProjectCard, ScrollUpBtn, ThemeMenu }